# Generated by Django 3.1.3 on 2020-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('profilephoto', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleORrent', models.CharField(default='', max_length=10)),
                ('propertytype', models.CharField(default='', max_length=50)),
                ('propertyphoto', models.ImageField(upload_to='images/')),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=50)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('buildingarea', models.CharField(default='', max_length=50)),
                ('carpetarea', models.CharField(default='', max_length=50)),
                ('transcationtype', models.CharField(default='', max_length=50)),
                ('propertyfloor', models.IntegerField()),
                ('totalfloor', models.IntegerField()),
                ('ownership', models.CharField(max_length=50)),
                ('availability', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('latitude', models.CharField(default='', max_length=50)),
                ('longitude', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
