# Generated by Django 3.1.3 on 2020-12-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profilepicture_propertydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='address'),
        ),
    ]
