# Generated by Django 3.1.3 on 2020-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
