# Generated by Django 3.1.3 on 2020-12-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201203_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='selleraddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
