# Generated by Django 3.1.3 on 2020-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201203_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='sellername',
            field=models.CharField(default='', max_length=100),
        ),
    ]
