# Generated by Django 3.1.3 on 2020-12-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_propertydetails_sellername'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='sellername',
            field=models.CharField(default='', max_length=100),
        ),
    ]
