# Generated by Django 3.1.3 on 2020-12-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_propertydetails_sellername'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertydetails',
            options={'ordering': ['-id']},
        ),
    ]
