# Generated by Django 3.1.3 on 2020-12-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201203_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
