# Generated by Django 3.1.3 on 2020-12-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_profilepicture_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='address',
        ),
    ]
