# Generated by Django 3.1.3 on 2020-12-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_profilepicture_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
