# Generated by Django 3.1.3 on 2020-12-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_propertydetails_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='recent_view',
            field=models.CharField(default='', max_length=100),
        ),
    ]
