# Generated by Django 3.1.3 on 2020-12-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_propertydetails_recent_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='recent_view',
        ),
    ]
