# Generated by Django 3.1.3 on 2020-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='myapp.PropertyDetails'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
