# Generated by Django 3.1.3 on 2020-12-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
